export const portfolioConfig = {
  name: "Elvis Lin",
  bio: "I’m a fullstack engineer who cares just as much about how things feel as how they function. With a strong eye for design, I build products that are thoughtful end to end, balancing clean architecture with intuitive, consistent user experiences.",
  resumeUrl: "/Elvis_Lin_Fullstack_Resume.pdf",
  projects: [
    {
      id: 1,
      title: "Photography and Film Portfolio",
      description: "A cinematic, minimalist portfolio website showcasing my photography and film skills. Built with pure HTML, CSS, and JavaScript to showcase my ability to create engaging, performant web experiences without relying on frameworks.",
      // imageUrl: "https://images.unsplash.com/photo-1481481600673-6140111ea51a",
      imageUrl: "/portfolio.png",
      link: "https://elvislin125.github.io/ElvisLinPhotography/",
      techStack: ["HTML", "CSS", "JavaScript"],
      featured: true,
    },
    {
      id: 2,
      title: "Bessy Preview Site",
      description: "A preview site for my startup, Bessy, an AI-powered fashion platform.",
      imageUrl: "/bessy.png",
      link: "https://bessy-website.vercel.app/",
      techStack: ["Next.js", "React", "Vercel", "Figma"],
      featured: false,
    },
    {
      id: 3,
      title: "AI Writing Assistant",
      description: "An AI-powered application that helps writers overcome block using LLMs.",
      imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead2708",
      link: "https://github.com",
      techStack: ["React", "Express", "OpenAI", "WebSockets"],
      featured: true,
    }
  ],
  experiences: [
    {
      id: 1,
      company: "Optum (Developer Portal)",
      role: "Fullstack Engineer",
      startDate: "2024",
      endDate: "Present",
      description: "Spearheaded implementation of a module federation architecture. Led the creation of service health monitoring dashboard.",
      skills: ["React", "TypeScript", "Java", "AWS", "Module Federation"],
    },
    {
      id: 2,
      company: "Optum (Design Systems)",
      role: "Frontend Engineer",
      startDate: "2023",
      endDate: "2024",
      description: "Built token-based theming system. Developed accessible React component library used by dozens teams across the organization.",
      skills: ["React", "TypeScript", "styled-components", "SASS", "Accessibility"],
    },
    {
      id: 3,
      company: "SAP",
      role: "Fullstack Developer Intern",
      startDate: "2022",
      endDate: "2022",
      description: "Implemented configuration-driven form generation. Accelerated feature development for partner teams.",
      skills: ["React", "Node.js", "Microsoft Teams Integration"],
    },
    {
      id: 4,
      company: "UnitedHealth Group",
      role: "Software Engineering Intern",
      startDate: "2022",
      endDate: "2022",
      description: "Built an automated tool to validate SSL certificates across 4,300+ ESXi hosts, saving over 12 hours of effort per day.",
      skills: ["Python", "Automation"],
    }
  ],
  skills: [
    { id: 1, category: "Frontend", name: "React / Next.js" },
    { id: 2, category: "Frontend", name: "TypeScript" },
    { id: 3, category: "Frontend", name: "Framer Motion" },
    { id: 4, category: "Frontend", name: "Tailwind CSS" },
    { id: 5, category: "Backend", name: "Node.js / Express" },
    { id: 6, category: "Backend", name: "PostgreSQL / Drizzle" },
    { id: 7, category: "Backend", name: "Redis" },
    { id: 8, category: "DevOps", name: "Docker / CI/CD" },
  ],
  contact: {
    email: "elvis@example.com",
    location: "California, USA",
    status: "Open to new opportunities",
  }
};
